# 1. Import Libraries

In [1]:
import pandas as pd

# 2. Load Dataset

In [2]:
df=pd.read_csv("../data/raw/online_retail_data.csv")

# 3. Dataset Overview

### 3.1 Dataset Shape

In [3]:
df.shape

(541909, 8)

### 3.2 Dataset Information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

### 3.3 Statistical Summary

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

### 3.4 Column Names

In [6]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

### 3.5 First Five Records

In [7]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

# 4. Data Quality Assessment

### 4.1 Missing Values

### *Missing Value Count*

In [8]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

### *Missing Value Percentage*

In [9]:
perc_miss=df.isna().sum()/len(df) 
perc_miss*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

### 4.2 Duplicate Rows

In [10]:
print(df.duplicated().sum())

5268

### 4.3 Data Types

In [11]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

### 4.4 Unique Values

In [12]:
df.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

### 4.5 Initial Anomaly Detection

### *Negative & Zero  Quantity*

In [13]:
df[df["Quantity"] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [14]:
print(len(df[df["Quantity"] < 0]))

10624

### *Negative & Zero Unit Price*

In [15]:
df[df["UnitPrice"] < 0].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [16]:
df[df["UnitPrice"] == 0].sample(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
405972,571723,85211,NaN,-1,2011-10-18 17:30:00,0.0,NaN,United Kingdom
150604,549465,84415B,NaN,-5,2011-04-08 14:22:00,0.0,NaN,United Kingdom
535321,581198,22025,check,-30,2011-12-07 18:26:00,0.0,NaN,United Kingdom
148089,549164,16169P,NaN,-75,2011-04-06 17:20:00,0.0,NaN,United Kingdom
143308,548682,72789,NaN,-2,2011-04-01 16:44:00,0.0,NaN,United Kingdom
94305,544347,22114,NaN,-4,2011-02-18 09:51:00,0.0,NaN,United Kingdom
192289,553394,15058A,wet/rusty,-30,2011-05-16 16:47:00,0.0,NaN,United Kingdom
471147,576619,21054,NaN,1,2011-11-15 17:01:00,0.0,NaN,United Kingdom
147793,549138,22988,NaN,12,2011-04-06 15:25:00,0.0,NaN,United Kingdom
282290,561639,84799,NaN,-346,2011-07-28 14:58:00,0.0,NaN,United Kingdom
146983,549034,16248B,NaN,2,2011-04-05 17:08:00,0.0,NaN,United Kingdom
150593,549454,84858C,NaN,46,2011-04-08 14:18:00,0.0,NaN,United Kingdom
22534,538173,22353,NaN,-28,2010-12-10 09:35:00,0.0,NaN,United Kingdom
143306,548680,72800D,NaN,-18,2011-04-01 16:43:00,0.0,NaN,United Kingdom
210963,555334,84805A,wet damaged,-96,2011-06-02 11:12:00,0.0,NaN,United Kingdom
319895,564914,85132C,damages,-109,2011-08-31 12:40:00,0.0,NaN,United Kingdom
133993,547813,84840,NaN,1,2011-03-25 14:11:00,0.0,NaN,United Kingdom
519986,580218,22577,check,-300,2011-12-02 12:12:00,0.0,NaN,United Kingdom
433458,573920,84050,check,14,2011-11-01 18:00:00,0.0,NaN,United Kingdom
404391,571674,23702,NaN,100,2011-10-18 13:22:00,0.0,NaN,United Kingdom

In [17]:

print(len(df[df["UnitPrice"] == 0]))

2515

In [18]:

print(len(df[df["UnitPrice"] < 0]))

2

# 5. Data Cleaning

### 5.1 Column Names

In [19]:
df.columns=df.columns.str.lower()

In [20]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country'],
      dtype='object')

### 5.2 Invoice Number

In [21]:
# No missing values or formatting issues detected.

### 5.3 Stock Code

In [22]:
# No missing values or formatting issues detected.

### 5.4 Description

In [23]:
df['description']=(df['description']
                   .str.lower()
                   .str.replace(" ","_")
                   .str.strip("_. ")
)

In [24]:
df = df[df['description'].notna()]

In [25]:
df['description'].sample(20)

206789        hot_water_bottle_i_am_so_poorly
213004            bread_bin_diner_style_ivory
539883                   black_kitchen_scales
71424     antique_tall_swirlglass_trinket_pot
189408                  regency_milk_jug_pink
161176               set_of_4_jam_jar_magnets
131007                 jumbo_storage_bag_suki
475080     set_of_72_retrospot_paper__doilies
169895                     lunch_bag_woodland
329240                    wall_tidy_retrospot
180403             watering_can_blue_elephant
271591         large_purple_babushka_notebook
218509          doormat_vintage_leaves_design
131908       pottering_in_the_shed_metal_sign
428508               alarm_clock_bakelike_red
146719           red_spot_ceramic_drawer_knob
132523             jigsaw_tree_with_birdhouse
76029              victorian_sewing_box_small
245825             recycled_acapulco_mat_pink
141080    clear_drawer_knob_acrylic_edwardian
Name: description, dtype: object

### 5.5 Quantity

In [26]:
# No missing values or formatting issues detected.

### 5.6 Invoice Date

In [27]:
df['invoicedate'] = pd.to_datetime(df['invoicedate'])

### 5.7 Unit Price

In [28]:
df = df[df["unitprice"] >= 0]

In [29]:
df = df[
    ~(
        df['description'].isna() &
        (df['unitprice'] == 0) &
        df['customerid'].isna()
    )
]

### 5.8 Customer ID

In [30]:
# Missing values retained as they may represent guest or unidentified customers.

### 5.9 Country

In [31]:
df['country']=(df['country']
               .str.lower()
               .str.replace(" ","_")
)

In [32]:
df.to_csv("../data/processed/online_retail_data_clean.csv",index=False)

# 6. Final Data Validation

### 6
.1 Dataset Shape

In [33]:
df.shape

(540453, 8)

### 6.2 Dataset Information

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 540453 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoiceno    540453 non-null  object
 1   stockcode    540453 non-null  object
 2   description  540453 non-null  object
 3   quantity     540453 non-null  int64
 4   invoicedate  540453 non-null  datetime64[ns]
 5   unitprice    540453 non-null  float64
 6   customerid   406829 non-null  float64
 7   country      540453 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 37.1+ MB

### 6.3 Statistical Summary

In [35]:
df.describe()

,quantity,invoicedate,unitprice,customerid
count,540453.000000,540453,540453.000000,406829.000000
mean,9.603161,2011-07-04 16:20:30.497305344,4.664472,15287.690570
min,-80995.000000,2010-12-01 08:26:00,0.000000,12346.000000
25%,1.000000,2011-03-28 11:49:00,1.250000,13953.000000
50%,3.000000,2011-07-20 11:38:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:49:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.008001,NaN,94.522031,1713.600303

### 6.4 Column Names

In [36]:
df.columns

Index(['invoiceno', 'stockcode', 'description', 'quantity', 'invoicedate',
       'unitprice', 'customerid', 'country'],
      dtype='object')

### 6.5 Sample Record

In [37]:
df.sample(10)

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
368614,568989,23200,jumbo_bag_pears,10,2011-09-29 16:41:00,2.08,14709.0,united_kingdom
307548,563922,22971,queens_guard_coffee_mug,1,2011-08-21 14:10:00,2.55,14529.0,united_kingdom
110448,545687,22859,easter_tin_bunny_bouquet,6,2011-03-06 12:20:00,1.65,17769.0,united_kingdom
471467,576644,82484,wood_black_board_ant_white_finish,1,2011-11-16 10:01:00,16.63,NaN,united_kingdom
125818,547062,22805,blue_drawer_knob_acrylic_edwardian,4,2011-03-20 13:28:00,1.25,16728.0,united_kingdom
244086,558475,22906,12_message_cards_with_envelopes,1,2011-06-29 15:58:00,3.29,NaN,united_kingdom
389225,570465,23534,wall_art_stop_for_tea,5,2011-10-10 16:02:00,12.46,NaN,united_kingdom
315631,564733,22893,mini_cake_stand_t-light_holder,10,2011-08-28 13:18:00,0.42,17841.0,united_kingdom
383042,C569989,22666,recipe_box_pantry_yellow_design,-23,2011-10-06 20:08:00,2.55,16839.0,united_kingdom
2476,536592,20617,first_class_passport_cover,1,2010-12-01 17:06:00,4.21,NaN,united_kingdom

# 7. Feature Engineering

## Revenue

## Year

## Month

## Day

## Hour

# 8. Exploratory Data Analysis

## 8.1 Univariate Analysis

## 8.2 Bivariate Analysis

## 8.3 Multivariate Analysis

## 8.4 Business Insights

# 9. Conclusion

## Key Findings

## Data Cleaning Summary

## Final Remarks